### ISSUE TITLE
__raft_logentry_poll() & __raft_logentry_pop

### ISSUE THREAD

**Issue by ghost** [willemt/ticketd#2]
Hi Willem,

Great work on the C raft implementation. I'm investigating whether we can use your library in a new project I'm working on.

Getting my head around the code, nothing building yet... but, it seems to me that when persisting log entries you create two records with and without the lsb set (`__raft_logentry_offer()`). These records can be considered a pair.

This is confirmed in `__load_commit_log()` where we can see these pairs must also appear sequentially.
However `mdb_poll()` & `mdb_pop()` remove single records, presumably breaking this.

I can see `__raft_logentry_poll()` is marked for future support. Just wondering why this hasn't been picked up before.

Looking forward to working on this.

Cheers,

Neil

**Comment by willemt** [comment]
Thanks for your message. Hope you can find the library useful!

ticketd is an open source showcase for how to use the library. It isn't used in production so there are potentially bugs that haven't been discovered yet sorry.

re: the lsb set on `__raft_logentry_offer()`. It looks like you've found a bug. I will update the code to remove the two records in `__raft_logentry_poll()` and `__raft_logentry_pop()`

re: `__raft_logentry_poll()`. This is strictly for log compaction, ie. you want to remove log entries from the front of the log after you've made a snapshot. ticketd doesn't showcase any log compaction atm. I'm planning on adding this soon.

**Comment by ghost** [comment]
Is the library in production use at the moment? That would certainly be reassuring to hear. I'm trying a single threaded implementation using Qt's event loop & asynchronous sockets. I'll let you know how I get on.

**Comment by willemt** [comment]
It's in-use in production. Please let me know how you get on :)
